[2025-10-04T14:10:53.402+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-04T14:10:53.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_hourly_etl.retail_transactions manual__2025-10-04T14:10:27.212560+00:00 [queued]>
[2025-10-04T14:10:53.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_hourly_etl.retail_transactions manual__2025-10-04T14:10:27.212560+00:00 [queued]>
[2025-10-04T14:10:53.511+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-04T14:10:53.548+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): retail_transactions> on 2025-10-04 14:10:27.212560+00:00
[2025-10-04T14:10:53.575+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'retail_hourly_etl', 'retail_transactions', 'manual__2025-10-04T14:10:27.212560+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/retail_hourly_etl.py', '--cfg-path', '/tmp/tmpdkpbucnc']
[2025-10-04T14:10:53.582+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask retail_transactions
[2025-10-04T14:10:53.614+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=194) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-04T14:10:53.616+0000] {standard_task_runner.py:64} INFO - Started process 195 to run task
[2025-10-04T14:10:53.820+0000] {task_command.py:426} INFO - Running <TaskInstance: retail_hourly_etl.retail_transactions manual__2025-10-04T14:10:27.212560+00:00 [running]> on host 34cb717f1e35
[2025-10-04T14:10:54.388+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retail_hourly_etl' AIRFLOW_CTX_TASK_ID='retail_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T14:10:27.212560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T14:10:27.212560+00:00'
[2025-10-04T14:10:54.400+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-04T14:10:54.531+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-04T14:10:54.552+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/public/retail_transactions.py || exit 3']
[2025-10-04T14:10:54.622+0000] {subprocess.py:86} INFO - Output:
[2025-10-04T14:10:55.596+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-04T14:10:55.599+0000] {subprocess.py:93} INFO -   File "/opt/***/public/retail_transactions.py", line 4, in <module>
[2025-10-04T14:10:55.607+0000] {subprocess.py:93} INFO -     from dbt.cli.main import cli
[2025-10-04T14:10:55.608+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'dbt'
[2025-10-04T14:10:55.649+0000] {subprocess.py:97} INFO - Command exited with return code 3
[2025-10-04T14:10:55.656+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-04T14:10:55.705+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 3.
[2025-10-04T14:10:55.741+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=retail_hourly_etl, task_id=retail_transactions, run_id=manual__2025-10-04T14:10:27.212560+00:00, execution_date=20251004T141027, start_date=20251004T141053, end_date=20251004T141055
[2025-10-04T14:10:55.805+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task retail_transactions (Bash command failed. The command returned a non-zero exit code 3.; 195)
[2025-10-04T14:10:55.866+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-04T14:10:55.938+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-04T14:10:55.952+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
