[2025-10-04T13:26:05.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-04T13:26:06.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_hourly_etl.source_transaction_lion_parcel manual__2025-10-04T13:24:58.430403+00:00 [queued]>
[2025-10-04T13:26:06.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_hourly_etl.source_transaction_lion_parcel manual__2025-10-04T13:24:58.430403+00:00 [queued]>
[2025-10-04T13:26:06.417+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-04T13:26:06.530+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): source_transaction_lion_parcel> on 2025-10-04 13:24:58.430403+00:00
[2025-10-04T13:26:06.723+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'retail_hourly_etl', 'source_transaction_lion_parcel', 'manual__2025-10-04T13:24:58.430403+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/retail_hourly_etl.py', '--cfg-path', '/tmp/tmpx8xhsyl_']
[2025-10-04T13:26:06.773+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask source_transaction_lion_parcel
[2025-10-04T13:26:06.764+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-04T13:26:06.785+0000] {standard_task_runner.py:64} INFO - Started process 179 to run task
[2025-10-04T13:26:07.717+0000] {task_command.py:426} INFO - Running <TaskInstance: retail_hourly_etl.source_transaction_lion_parcel manual__2025-10-04T13:24:58.430403+00:00 [running]> on host 95136845f4d3
[2025-10-04T13:26:10.390+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retail_hourly_etl' AIRFLOW_CTX_TASK_ID='source_transaction_lion_parcel' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T13:24:58.430403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T13:24:58.430403+00:00'
[2025-10-04T13:26:10.405+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-04T13:26:11.049+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-04T13:26:11.076+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/public/source_transaction_lion_parcel.py || exit 3']
[2025-10-04T13:26:11.215+0000] {subprocess.py:86} INFO - Output:
[2025-10-04T13:26:30.872+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-04T13:26:30.874+0000] {subprocess.py:93} INFO -   File "/opt/***/public/source_transaction_lion_parcel.py", line 13, in <module>
[2025-10-04T13:26:30.877+0000] {subprocess.py:93} INFO -     from etl import connection
[2025-10-04T13:26:30.878+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'etl'
[2025-10-04T13:26:31.615+0000] {subprocess.py:97} INFO - Command exited with return code 3
[2025-10-04T13:26:31.634+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-04T13:26:31.684+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 3.
[2025-10-04T13:26:31.713+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=retail_hourly_etl, task_id=source_transaction_lion_parcel, run_id=manual__2025-10-04T13:24:58.430403+00:00, execution_date=20251004T132458, start_date=20251004T132606, end_date=20251004T132631
[2025-10-04T13:26:31.784+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task source_transaction_lion_parcel (Bash command failed. The command returned a non-zero exit code 3.; 179)
[2025-10-04T13:26:31.862+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-04T13:26:31.980+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-04T13:26:31.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
